[project]
name = "base-sulpaa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "streamlit>=1.52.1",
    "supabase>=2.25.1",
]
